// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// permute_null_cpp
List permute_null_cpp(NumericVector pool_z, int sz, int n_perm, int seed, bool compute_gini, bool compute_cv);
RcppExport SEXP _DSGEr_permute_null_cpp(SEXP pool_zSEXP, SEXP szSEXP, SEXP n_permSEXP, SEXP seedSEXP, SEXP compute_giniSEXP, SEXP compute_cvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pool_z(pool_zSEXP);
    Rcpp::traits::input_parameter< int >::type sz(szSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_gini(compute_giniSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_cv(compute_cvSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_null_cpp(pool_z, sz, n_perm, seed, compute_gini, compute_cv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DSGEr_permute_null_cpp", (DL_FUNC) &_DSGEr_permute_null_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DSGEr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
